### ISSUE TITLE
Not Opened

### ISSUE THREAD

**Issue by Peaty11** [Apophis52/Python-Mass-DM-Selfbot#14]
The Python File got open, after 1 sec hes closing.

**Comment by Apophis52** [comment]
Open it in command prompt annd send me the error.

**Comment by Peaty11** [comment]
![Index](https://user-images.githubusercontent.com/104279735/165834391-c7ad7a6f-239e-4482-a07a-8759dde2f109.png)

**Comment by Apophis52** [comment]
You are suppsoed to type "python index.py" in normall console not interactive python shell

**Comment by Peaty11** [comment]
What is my fault?



![index2](https://user-images.githubusercontent.com/104279735/165835713-be8d8624-9ef8-439f-bdfc-e76b1e9ee282.png)

**Comment by Apophis52** [comment]
Run pip install discum like the instructions say to
