### ISSUE TITLE
TREACESBACK ERROR

### ISSUE THREAD

**Issue by Chigopen** [Apophis52/Python-Mass-DM-Selfbot#15]
![image](https://user-images.githubusercontent.com/98891318/165885720-2f757bc7-eeb2-4da6-aa8b-18aea3632385.jpg)
After installing Pip command and I run python index.py I keep getting tracesback error pls I need help here…… # #

**Comment by Apophis52** [comment]
This is either a library issue with discum, or you put one of the IDs in wrong.
